name: Deploy Emmacarena to vServer

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Deploy to vServer using SSH Action
      - name: Deploy to vServer
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VSERVER_HOST }}
          username: ${{ secrets.VSERVER_USER }}
          key: ${{ secrets.VSERVER_SSH_KEY }}
          port: 22
          debug: true
          script: |
            whoami
            pwd
            cd /home/tim/clodolt-dev || exit 1
            echo "Changed directory"
            git pull origin master
            echo "Pulled latest code"
            npm install
            echo "Installed dependencies"
            npm run build
            echo "Built application"
            pm2 delete clodolt-dev || true
            pm2 start npm --name "clodolt-dev" -- start
            echo "Restarted application"
